# Generated by Django 4.1.7 on 2023-03-23 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название категории')),
                ('short_description', models.CharField(blank=True, max_length=64, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name_plural': 'Категории ресторанов',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Название ресторана')),
                ('image', models.ImageField(blank=True, upload_to='restaurant_images', verbose_name='Логотип')),
                ('short_description', models.CharField(blank=True, max_length=64, verbose_name='Короткое описание')),
                ('city', models.CharField(choices=[('Норильск', 'Норильск'), ('Талнах', 'Талнах'), ('Каейркан', 'Каейркан'), ('Дудинка', 'Дудинка')], max_length=10, verbose_name='Город')),
                ('adress', models.CharField(max_length=128, verbose_name='Адрес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurantcategory', verbose_name='Категория ресторана')),
            ],
            options={
                'verbose_name_plural': 'Заведения',
            },
        ),
    ]
