# Generated by Django 4.1.7 on 2023-03-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(choices=[('Норильск', 'Норильск'), ('Талнах', 'Талнах'), ('Каейркан', 'Каейркан'), ('Дудинка', 'Дудинка'), ('Дуд', 'Дуд')], max_length=10, verbose_name='Город'),
        ),
    ]
