# Generated by Django 4.1.7 on 2023-03-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='perm',
        ),
    ]
