# Generated by Django 4.1.7 on 2023-03-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_access_rights'),
        ('restaurant', '0004_remove_restaurant_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='perm',
            field=models.ManyToManyField(to='user.rightuser', verbose_name='Группы прав'),
        ),
    ]
