# Generated by Django 4.1.7 on 2023-04-25 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_perm_restaurant_perm_grup_fo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('number_week', models.IntegerField(max_length=2, verbose_name='№ недели')),
                ('weekdays', models.CharField(choices=[('Пн', 'Пн'), ('Вт', 'Вт'), ('Ср', 'Ср'), ('Чт', 'Чт'), ('Пт', 'Пт'), ('Сб', 'Сб'), ('Вс', 'Вс')], max_length=2, verbose_name='День недели')),
                ('revenue', models.IntegerField(max_length=9, verbose_name='Выручка')),
                ('cost_price', models.IntegerField(max_length=9, verbose_name='Себестоимость')),
                ('number_of_checks', models.IntegerField(max_length=3, verbose_name='Количество чеков')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant', verbose_name='Наименование ресторана')),
            ],
        ),
    ]
