# Generated by Django 4.1.7 on 2023-04-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'Данные для отчетов'},
        ),
        migrations.AlterField(
            model_name='report',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='report',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Выручка'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('department', 'data')},
        ),
    ]
