# Generated by Django 4.1.7 on 2023-04-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_report_options_alter_report_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_of_checks',
            field=models.IntegerField(max_length=4, verbose_name='Количество чеков'),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_week',
            field=models.IntegerField(max_length=4, verbose_name='№ недели'),
        ),
        migrations.AlterField(
            model_name='report',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Выручка'),
        ),
        migrations.AlterField(
            model_name='report',
            name='weekdays',
            field=models.CharField(choices=[('Пн', 'Пн'), ('Вт', 'Вт'), ('Ср', 'Ср'), ('Чт', 'Чт'), ('Пт', 'Пт'), ('Сб', 'Сб'), ('Вс', 'Вс')], max_length=3, verbose_name='День недели'),
        ),
    ]
