# Generated by Django 4.1.7 on 2023-04-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_report_weekdays'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
    ]
