# Generated by Django 4.1.7 on 2023-04-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('department', 'data', 'number_week')},
        ),
    ]
