# Generated by Django 4.1.7 on 2023-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='weekdays',
            field=models.CharField(max_length=2, verbose_name='День недели'),
        ),
    ]
