# Generated by Django 4.1.7 on 2023-04-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_alter_report_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='weekdays',
            field=models.CharField(choices=[('Пн', 'Пн'), ('Вт', 'Вт'), ('Ср', 'Ср'), ('Чт', 'Чт'), ('Пт', 'Пт'), ('Сб', 'Сб'), ('Вс', 'Вс')], max_length=10, verbose_name='День недели'),
        ),
    ]
