# Generated by Django 4.1.7 on 2023-04-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='number_of_checks',
            field=models.IntegerField(verbose_name='Количество чеков'),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_week',
            field=models.IntegerField(verbose_name='№ недели'),
        ),
    ]
