# Generated by Django 4.1.7 on 2023-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_alter_report_number_of_checks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_report', models.CharField(max_length=15, verbose_name='Вид отчета')),
                ('short_description', models.CharField(blank=True, max_length=64, verbose_name='Краткое описание отчета')),
            ],
        ),
    ]
