# Generated by Django 4.1.7 on 2023-04-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_reporttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttype',
            options={'verbose_name_plural': 'Виды отчета'},
        ),
    ]
