# Generated by Django 4.1.7 on 2023-04-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_alter_reporttype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='name_report',
            field=models.CharField(max_length=20, verbose_name='Вид отчета'),
        ),
    ]
