# Generated by Django 4.1.7 on 2023-03-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_user_access_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название права доступа')),
                ('where_is_access', models.CharField(blank=True, max_length=64, verbose_name='Куда имеется доступ')),
            ],
            options={
                'verbose_name_plural': 'Права доступа',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='access_rights',
        ),
    ]
