# Generated by Django 4.1.7 on 2023-03-28 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rightuser_remove_user_access_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_rights',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='user.rightuser', verbose_name='Права доступа пользователя'),
            preserve_default=False,
        ),
    ]
