# Generated by Django 4.1.7 on 2023-03-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_access_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_employee',
            field=models.BooleanField(default=False, verbose_name='Пользователь проверен и выданы права'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_rights',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='user.rightuser', verbose_name='Права доступа пользователя'),
        ),
    ]
