# Generated by Django 4.1.7 on 2023-03-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_verified_employee_alter_user_access_rights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified_employee',
        ),
    ]
